# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ebb4b4b31c451a459f1c5fce8dbc3c3099d04b777a6bf23fd0277add14bb4973d292e1cfd6c838f3980c07230a79d8b9cf8483805ed46ca11670a4e5bfbf14

test:
  secret_key_base: af5ce69cdfd10ac58e283c9ad073bf27ebba1e5eabb4d348662c9878fe8fdb1af2ae39a47aaf0d6522b033f521e5395e355b98bd385104fc63291b85899b3a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
